# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  # In create-storage-account.yml
  - task: AzureCLI@2
    displayName: 'Create Storage Account'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # The task already logs in and sets the subscription.
        # This command just ensures the context is re-affirmed before the create command.
        az account set --subscription $env:AZURE_SUBSCRIPTION_ID
        az storage account create --name $(terraform_st_storage_account) --resource-group $(terraform_st_resource_group) --location $(location) --sku Standard_LRS
